language: ruby
rvm:
  #- 1.8.7 # no, since it doesn't get fun(a, *b, c)
  - 1.9.3
  - 2.1.1
  - 2.2.2
  #- jruby-18mode
  - jruby-19mode
  #- jruby-20mode
script: bundle exec rspec
branches:
  only:
    - master
  #except:
  #  - master

sudo: false
cache: bundler

